### ISSUE TITLE
change pg_down key binding

### ISSUE THREAD

**Issue by mrzl** [armadillu/ofxTimeMeasurements#5]
Hey,

first off, thank you for this addon, its a real beauty and saved myself many tears. *But*, how do I change the page_down key binding in order to hide the frame? I can't seem to find any traces in the code and I'm slightly puzzled. 

Thanks already,
Marcel

**Comment by mrzl** [comment]
Well, in the meanwhile I cam across the setEnabled() function.. I'd still be interested in finding out, where you specifiy that key.

**Comment by armadillu** [comment]
It's all in the headers; I believe this is what you want:
```
unsigned char myKey = 'E';
TIME_SAMPLE_GET_INSTANCE()->setGlobalEnableDisableKey(myKey);
```

**Comment by mrzl** [comment]
Thanks.
